---
# Check if Drupy theme exist
- name: Check if Drupy theme exists in the specified path
  ansible.builtin.stat:
    path: '{{ ansistrano_release_path.stdout }}/web/themes/custom/{{ vault_theme_name }}'
  register: theme_exists
  # tags:
  #   - ini_theming

# Install theme
- name: Install Drupal theme using Drush
  ansible.builtin.command:
    cmd: 'drush theme:install {{ vault_theme_name }} -y'
    chdir: '{{ ansistrano_release_path.stdout }}/web/themes/custom/'
  when: theme_exists.stat.exists
  tags:
    - ini_theming

# Set theme as default
- name: Set Drupal theme as default
  ansible.builtin.command:
    cmd: 'drush config-set system.theme default {{ vault_theme_name }} -y'
    chdir: '{{ ansistrano_release_path.stdout }}/web/'
  when: theme_exists.stat.exists
  tags:
    - ini_theming

# Set permissionas to theme
- name: Ensure properly permissions to Theme's directory
  file:
    path: '{{ ansistrano_release_path.stdout }}/web/themes/custom/{{ vault_theme_name }}'
    mode: '0755'
    state: directory
    owner: '{{ vault_server_client }}'
    group: '{{ vault_server_group }}'
    recurse: true
  when: theme_exists.stat.exists
  tags:
    - ini_theming

# Rebuild Drupal cache
- name: Rebuild Drupal cache using Drush
  shell: |
    {{ release_drush_path }}
  args:
    chdir: '{{ release_drupal_path }}'
    executable: /bin/bash
  tags:
    - drupal
